//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tool73.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_Tool73TYPE                  130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_EDIT_MENU                   306
#define IDD_MYFORM                      310
#define IDD_MAPTOOL                     312
#define IDD_TILETOOL                    313
#define IDD_OBJECTTOOL                  314
#define IDD_EVENTTOOL                   315
#define IDD_PATHFIND                    316
#define IDD_UNITTOOL                    320
#define IDC_BUTTON1                     1009
#define IDC_BUTTON_MAP                  1009
#define IDC_BUTTON_OBJSETSAVE           1009
#define IDC_BUTTON_TILESAVE             1009
#define IDC_BUTTON_NarrAdmit            1009
#define IDC_RADIO1                      1010
#define IDC_RADIO2                      1011
#define IDC_RADIO3                      1012
#define IDC_CHECK_WEAPON                1013
#define IDC_CHECK_ARMOR                 1014
#define IDC_CHECK_POTION                1015
#define IDC_BUTTON_BITAMAP              1017
#define IDC_BUTTON_UNIT                 1018
#define IDC_BUTTON_SAVE_ALL             1019
#define IDC_BUTTON_LOAD_ALL             1020
#define IDC_BUTTON_LOAD2                1021
#define IDC_BUTTON_EVENTSAVE            1021
#define IDC_CHECK_COLLISION             1022
#define IDC_SLIDER_HIGH                 1023
#define IDC_LISTBOX_TILE                1024
#define IDC_COMBO_TILE                  1025
#define IDC_COMBO1                      1026
#define IDC_COMBO_MAP                   1026
#define IDC_LIST1                       1027
#define IDC_LIST_OBJECT_IMAGELIST       1027
#define IDC_CHECK1                      1028
#define IDC_CHECK_OBJ_COLLISION         1028
#define IDC_CHECK2                      1029
#define IDC_CHECK_OBJ_DESTROY           1029
#define IDC_EDIT1                       1030
#define IDC_EDIT_OBJECT_OK              1030
#define IDC_EDIT_OBJ_HP                 1030
#define IDC_EDIT_MONSTER_HP             1030
#define IDC_EDIT_SCRIPT                 1030
#define IDC_CHECK3                      1031
#define IDC_CHECK_OBJ_HP                1031
#define IDC_EDIT2                       1031
#define IDC_EDIT_MONSTER_ATT            1031
#define IDC_EDIT_NARR_NAME              1031
#define IDC_BUTTON_OBJECTADMIT          1032
#define IDC_BUTTON2                     1033
#define IDC_STATIC_SCRIPT               1034
#define IDC_STATIC_SOUND                1035
#define IDC_LIST2                       1036
#define IDC_LIST_SOUNDFILE              1036
#define IDC_BUTTON_EVENTADMIT           1037
#define IDC_LIST_SCRIPT                 1038
#define IDC_BUTTON_EVENTLOAD            1039
#define IDC_LIST_EVENT                  1040
#define IDC_BUTTON_PATHFINDER           1041
#define IDC_LIST_PATH_FIND              1042
#define IDC_BUTTON_PATH_SAVE            1043
#define IDC_BUTTON_PATH_LOAD            1044
#define IDC_BUTTON_PATHDELETE           1045
#define IDC_STA                         1046
#define IDC_TILE_IMAGE                  1046
#define IDC_BUTTON_TILESETSAVE          1047
#define IDC_SLIDER1                     1048
#define IDC_SLIDER_TILESIZE             1048
#define IDC_SLIDER_OBJECT_SCALE         1048
#define IDC_STATIC_OBJECT               1049
#define IDC_BUTTON_TILE_ERASE           1050
#define IDC_SLIDER2                     1052
#define IDC_SLIDER_GARO                 1052
#define IDC_SLIDER_OBJ_HITBOX_X         1052
#define IDC_STATIC_GARO                 1053
#define IDC_SLIDER_OBJ_HITBOX_Y         1053
#define IDC_SLIDER_OBJ_HITBOX_X2        1054
#define IDC_CHECK_TILE_COLLISION        1055
#define IDC_SLIDER_OBJ_HITBOX_Y2        1055
#define IDC_STATIC_IMAGELIST            1057
#define IDC_BUTTON_OBJERASE             1058
#define IDC_EDIT_XPOS                   1059
#define IDC_EDIT_YPOS                   1060
#define IDC_STATIC_XPOS                 1061
#define IDC_STATIC_YPOS                 1062
#define IDC_STATIC_OBJECTSCALE          1065
#define IDC_STATIC_OBJ_HITBOX_X         1066
#define IDC_STATIC_OBJ_HITBOX_Y         1067
#define IDC_BUTTON_OBJHITBOX            1068
#define IDC_BUTTON_TILE_LOAD            1069
#define IDC_STATIC_OBJ_HITBOX_X2        1069
#define IDC_BUTTON_OBJ_LOAD             1070
#define IDC_STATIC_OBJ_HITBOX_Y2        1071
#define IDC_COMBO_MONSTER               1072
#define IDC_STATIC_MONSTER              1073
#define IDC_BUTTON_MONSTER_SAVE         1074
#define IDC_BUTTON_MONSTER_LOAD         1075
#define IDC_BUTTON_MONSTER_DELETE       1076
#define IDC_BUTTON_MONSTER_ADMIT        1077
#define IDC_STATIC_MONSER_HP            1079
#define IDC_STATIC_MONSER_ATT           1080
#define IDC_BUTTON_NarrErase            1080

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           318
#endif
#endif
